services:
    app:
        container_name: "ccinvoice"
        build:
            context: ./
            dockerfile: dev.dockerfile
        volumes:
            - ./:/app
        ports:
            - 3000:3000
            - 8080:8080
