name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASS: ${{ secrets.SMTP_PASS }}
  FROM_NAME: Harry Potter
  FROM_ADDRESS: 4 Privet Drive
  FROM_CITY: Little Whinging, Surrey
  ACCOUNT_NUMBER: 1234567890-1234
  BASE_URL: https://duckduckgo.com/?q=

jobs:
  test:
    name: Test ccinvoice
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install wkhtmltopdf

    - name: Go Test
      # This is specifically for generating PDFs - setting this variable means we don't have to run the server to provide the HTML
      # response for wkhtmltopdf to create the PDF from. We're only testing the file is created and placed in the right directory,
      # so the content doesn't really matter.
      run: go test -v -cover 
